name: Cypress Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: build

  ui-chrome-tests:
      runs-on: ubuntu-latest
      needs: install
      container: cypress/browsers:node12.18.3-chrome87-ff82
      strategy:
        fail-fast: false
        matrix:
          containers: [1, 2]
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Download the build folders
          uses: actions/download-artifact@v2
          with:
            name: build
            path: build

        - name: 'UI Tests - Chrome'
          uses: cypress-io/github-action@v4
          with:
            install: false
            browser: chrome
            record: true
            parallel: true
            group: 'UI - Chrome'
            spec: cypress/specs/*
          env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}