name: Cypress Regression Tests

on: 
  push: 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ui-chrome-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          record: true
          parallel: true
          group: 'UI - Chrome'
          spec: cypress/specs/*
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}