name: Cypress Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    container: cypress/included:9.6.1
    steps:
      - name: Checkout
        - uses: actions/checkout@v2

      - name: UI Tests - Chrome
      - run: npm run test:headless

    - name: Save screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

    - name: Save videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos 