name: Cypress Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.0-chrome99-ff97
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
          run: |
            npm install

  ui-chrome-tests:
      runs-on: ubuntu-latest
      container: cypress/browsers:node16.14.0-chrome99-ff97
      strategy:
        fail-fast: false
        matrix:
          containers: [1, 2]
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: 'UI Tests - Chrome'
          uses: cypress-io/github-action@v2
          with:
            install: false
            browser: chrome
            record: true
            parallel: true
            group: 'UI - Chrome'
            spec: cypress/specs/*
          env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}